github: []
patreon:
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee: antonjijo2f
thanks_dev:
custom: "https://buymeacoffee.com/antonjijo2f"
